version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Specify the path to your ReactJS frontend code
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend  # Specify the path to your Java Spring Boot backend code
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_classroom
      MYSQL_USER: root
      MYSQL_PASSWORD: 20120232
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
