database:
  name: db_classroom
  host: localhost
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}
    username: 20120232
    password: 20120232
    driver-class-name: com.mysql.cj.jdbc.Driver