server:
  port: 5000
  servlet:
    context-path: /api/v1


spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
      host: ${MAIL_HOST}
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      port: ${MAIL_PORT}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB



application:
  security:
    jwt:
      secret-key: "4uENrgkVDBLCHntCtrN1u6vzwq3kVJDH9Z9qBjgBPrXdAZe4syzpQ970Z61sw1GyLDQidkb5vLSZXCVbni1f2Q=="
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    oauth2:
      google:
        client-id: "228097325596-si80lhvch9q4g7gmqj5e7cvrilca63p5.apps.googleusercontent.com"

