server:
  port: 5000
  servlet:
    context-path: /api/v1


spring:
  profiles:
    active: railway
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB



application:
  security:
    jwt:
      secret-key: "4uENrgkVDBLCHntCtrN1u6vzwq3kVJDH9Z9qBjgBPrXdAZe4syzpQ970Z61sw1GyLDQidkb5vLSZXCVbni1f2Q=="
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

