database:
  name: db_classroom
  host: monorail.proxy.rlwy.net
  port: 33312

spring:
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}
    username: root
    password: aBfd3GbcgDdGfAfBd5BF-D5c2gFE4H6F
    driver-class-name: com.mysql.cj.jdbc.Driver